# name: Main changed - build, then release and update GH Pages
# on:
#   push:
#     branches:
#       - main
# jobs:
#   build:
#     uses: ./.github/workflows/reusable-build.yml
#     with:
#       node-version: 16.6.2


#   update-storybook-on-ghpages:
#     runs-on: ubuntu-latest
#     needs: build
#     steps:
#       - name: Checkout ğŸ›ï¸
#         uses: actions/checkout@v3.0.2

#       - uses: ./.github/actions/cache-restore
#         id: cache-node-modules
#         with:
#           node-version: 16.6.2

#       - name: Build storybook
#         run: |
#           # yarn run test:generate-output
#           yarn run build-storybook -- --quiet --loglevel silent

#       - name: Deploy ğŸš€
#         uses: JamesIves/github-pages-deploy-action@v4.4.0
#         with:
#           branch: gh-pages # The branch the action should deploy to.
#           folder: storybook-static # The folder the action should deploy.