# name: GH Pages
# on:
#   push:
#     branches:
#       - main
# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout ğŸ›ï¸
#         uses: actions/checkout@v3.0.2

#       - name: Install and Build ğŸ”§ # This example project is built using yarn and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
#         run: |
#           yarn install --frozen-lockfile
#           # yarn run test:generate-output
#           yarn run build-storybook

#       - name: Deploy ğŸš€
#         uses: JamesIves/github-pages-deploy-action@v4.4.0
#         with:
#           branch: gh-pages # The branch the action should deploy to.
#           folder: storybook-static # The folder the action should deploy.
